name: Docker Container

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '3 8 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: scys/nginx:alpine,scys/nginx:latest

      - name: Run nginx -V and njs -v
        run: |
          docker run --rm -t scys/nginx nginx -V | sed 's/\-\-/\n\t--/g' | tee
          echo "njs v$(docker run -t scys/nginx njs -v)"
          
      - name: Test njs command line
        run: |
          echo "console.log('Using njs v' + njs.version)" | docker run -i --rm scys/nginx njs -q | grep "Using njs v0.7.7"