name: Docker Container

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '3 8 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Alpine
        uses: docker/build-push-action@v2
        with:
          context: ./docker_alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:alpine

      - name: Build Default
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest